version: '3.8'

networks:
  db_net:
    name: db_net
    driver: bridge

volumes:
  mongodatavolume:
    driver: local

services:
  node:
    build:
      dockerfile: ./docker/node/Dockerfile
      context: .
    ports:
      - '${APP_PORT}:3000'
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn start:dev"
    networks:
      - db_net
    depends_on:
      - db

  db:
    image: mongo:5.0
    environment:
      MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    volumes:
      - mongodatavolume:/data/db
      - ./docker/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - '${MONGO_PORT}:27017'
    networks:
      - db_net
      
  adminer:
    build:
      context: .
      dockerfile: ./docker/adminer/Dockerfile
    ports:
      - '8081:8080'
    networks:
      - db_net
    depends_on:
      - db