version: '3.8'

services:
  node:
    build:
      dockerfile: ./docker/node/Dockerfile
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn start:dev"