version: '3.8'

networks:
  app_net:
    driver: bridge

services:
  node:
    build:
      dockerfile: ./docker/node/Dockerfile
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn start:dev"
    networks:
      - app_net
  
  db:
    image: postgres:11.11
    volumes:
      - ./docker/db/postgres:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - 54320:5432
    networks:
      - app_net

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - app_net
    depends_on:
      - db
